### PR TITLE
Add `MappedPropertyPopulator` and related configuration

### PR DESCRIPTION
**Pull request by jdreesen**
This is a successor of the `SamePropertyPopulator` from #23 (which is removed in the PR) and a more generic version of the `ConverterPopulator` from #25 (which still exists as a special version of the `MappedPropertyPopulator`).

It supports not only the population of fields with the same name, but also of fields with different names. The hard work is done by the `symfony/property-access` component.

In addition, it supports "mapping" the value in between, using a `Closure`.

There is also accompanying configuration support.

### CODE REVIEW

**Comment by mike4git** [comment]
Isn't it ready for review?! We have talked about it yesterday. What do you miss?

**Comment by jdreesen** [comment]
The removal of the `SamePropertyPopulator` for example, as we agreed yesterday ;)

**Comment by jdreesen** [comment]
Apart from the docs, I'd consider this as ready.

The latest changes are:
- allow "mapping" of the value in between, using a Closure
- removed the `SamePropertyPopulator` and the `PropertyValueExtractor`
- changed the `ConverterPopulator` to be a special version of the `MappedPropertyPopulator`

**Comment by jdreesen** [comment]
This is ready now.

**Review by mike4git — APPROVED** [review]
Well done - reusage of MappedPropertyPopulator for ConverterPopulator

**Pull request merged**
