### PR TITLE
Allow any object as context

### PR DESCRIPTION
**Pull request by jdreesen**
This removes the necessity of the context (`$ctx`) being an implementation of `ConverterContext` and allows any object as context instead.

It will allow users to create specific, typed context objects for every converter use case instead of being forced to use a general one with an unspecific getter which cannot be typed.

> **Note**
> This is a BC break. But please wait with releasing a new major, as there are some more to come 😉

### CODE REVIEW

**Comment by mike4git** [comment]
Brain: We must prepare for tomorrow night.
Pinky: Why? What are we going to do tomorrow night?
Brain: The same thing we do every night, Pinky - try to take over the world!

**Comment by mike4git** [comment]
I don't know how you start your tests but for me they are not running if the TestKernel class is like this.
So I had to move it and change some code...

**Review by mike4git — APPROVED** [review]
Except the testing problem everything would be fine for me

**Comment by jdreesen** [comment]
I just start them via PhpStorm or `composer tests`. What's the error message you get?

**Review by mike4git — APPROVED** [review]

**Comment by jdreesen** [comment]
Does `composer dump` help?

**Comment by jdreesen** [comment]
I'm merging this, as the not-running tests are not related to this PR.

**Pull request merged**
